### PR TITLE
Add some content

### PR DESCRIPTION
**Pull request by ArnaudCalmettes**

### CODE REVIEW

**Comment by ArnaudCalmettes** [comment]
Random comment.

**Comment by Ge0** [comment]
@bert-e help

**Comment by ArnaudCalmettes** [comment]
Fixed.

**Comment by ArnaudCalmettes** [comment]
Try again

**Comment by ArnaudCalmettes** [comment]
Okay, now you should be okay

**Comment by ArnaudCalmettes** [comment]
@bert-e help

**Comment by ArnaudCalmettes** [comment]
@bert-e status

**Comment by eve-scality** [comment]
That's a cool pull request. :)

**Comment by eve-scality** [comment]
@bert-e reset

**Pull request merged**
